#!/usr/bin/env python3
"""
SMS Logger — SMS/MMS ingestion, per-contact log, dashboard, Obsidian export,
and a read-only JSON API for downstream consumers (e.g. an AI assistant).

No LLM lives here — an assistant can consume the API and optionally answer
active-mode messages via ASSISTANT_REPLY_URL, but logging never depends on one.
"""
from __future__ import annotations

import re
import hmac
import base64
import logging
import threading
import time
from datetime import datetime
import sys, os
from flask import Flask, request, jsonify, send_from_directory, Response, render_template, redirect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from functools import wraps

load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from smslog.db import (
    init_db, get_db, save_message, save_observed, load_index, load_profile,
    get_contact_name, save_contact_notes, get_message_history, merge_contact,
    get_all_contacts, search_messages, _relative_time, _phone_enc, _phone_dec,
)
from smslog.identity import resolve_key

# ── Config ────────────────────────────────────────────────────────────────────

OWNER_NAME         = os.getenv("OWNER_NAME", "")
WEBHOOK_SECRET     = os.getenv("WEBHOOK_SECRET", "")
DASHBOARD_USER     = os.getenv("DASHBOARD_USER", "admin")
DASHBOARD_PASSWORD = os.getenv("DASHBOARD_PASSWORD", "")

_LOG_PATH = os.getenv("SMS_LOG_PATH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "logs", "smslogger.log"))
os.makedirs(os.path.dirname(_LOG_PATH), exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    handlers=[
        logging.StreamHandler(),
        __import__("logging.handlers", fromlist=["RotatingFileHandler"])
            .RotatingFileHandler(_LOG_PATH, maxBytes=1_000_000, backupCount=3),
    ],
)

app = Flask(__name__)
limiter = Limiter(get_remote_address, app=app, default_limits=["60 per minute"])

# ── Auth ──────────────────────────────────────────────────────────────────────

def _require_dashboard_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not DASHBOARD_PASSWORD:
            return f(*args, **kwargs)
        if not auth or not (auth.username == DASHBOARD_USER and auth.password == DASHBOARD_PASSWORD):
            return Response("Login Required", 401, {"WWW-Authenticate": 'Basic realm="Login Required"'})
        return f(*args, **kwargs)
    return decorated


def _require_auth():
    if WEBHOOK_SECRET and not hmac.compare_digest(
        request.headers.get("X-Webhook-Secret", ""), WEBHOOK_SECRET
    ):
        return jsonify({"error": "unauthorized"}), 401
    return None

# ── Setup wizard ──────────────────────────────────────────────────────────────

def _is_configured():
    # Logging needs an owner name and a webhook secret — nothing else.
    return bool((os.getenv("OWNER_NAME") or OWNER_NAME) and (os.getenv("WEBHOOK_SECRET") or WEBHOOK_SECRET))


@app.before_request
def _check_setup():
    if not _is_configured() and request.path not in ("/setup", "/setup/init") and not request.path.startswith("/static"):
        return redirect("/setup")


@app.route("/", methods=["GET", "HEAD"])
def index():
    return redirect("/dashboard" if _is_configured() else "/setup")


@app.route("/setup")
def setup_wizard():
    return render_template("setup/wizard.html")


@app.route("/setup/init", methods=["POST"])
def setup_init():
    global OWNER_NAME, WEBHOOK_SECRET, DASHBOARD_PASSWORD
    name = request.form.get("owner_name", "").strip()
    number = re.sub(r"\D", "", request.form.get("owner_number", ""))
    secret = request.form.get("webhook_secret", "").strip()

    env_content = f"""# SMS Logger configuration (generated by wizard)
OWNER_NAME={name}
OWNER_NUMBERS={number}
WEBHOOK_SECRET={secret}
DASHBOARD_USER=admin
DASHBOARD_PASSWORD={secret}
TIMEZONE={os.getenv("TIMEZONE", "America/New_York")}
DB_PATH=/app/data/conversations.db
"""
    with open(".env", "w") as f:
        f.write(env_content)

    os.environ["OWNER_NAME"] = name
    os.environ["OWNER_NUMBERS"] = number
    os.environ["WEBHOOK_SECRET"] = secret
    os.environ["DASHBOARD_PASSWORD"] = secret
    OWNER_NAME, WEBHOOK_SECRET, DASHBOARD_PASSWORD = name, secret, secret
    return redirect("/dashboard")

# ── Dashboard ─────────────────────────────────────────────────────────────────

def _decorated_contact(c: dict) -> dict:
    """Shape a get_all_contacts() row for the templates."""
    name = c["name"]
    initials = "".join(w[0].upper() for w in name.split()[:2]) if name else "?"
    return {
        "phone": c["key"], "phone_enc": _phone_enc(c["key"]), "name": name,
        "initials": initials, "notes": "",
        "memory_count": c["message_count"],  # template shows this count badge
        "last_seen": _relative_time(c["last_seen"], datetime.utcnow()) if c["last_seen"] else None,
    }


@app.route("/dashboard")
@_require_dashboard_auth
def dash_home():
    contacts = [_decorated_contact(c) for c in get_all_contacts()]
    return render_template("dashboard.html", page="home", contacts=contacts, nudge_count=0)


@app.route("/dashboard/contact/<phone_enc>")
@_require_dashboard_auth
def dash_contact(phone_enc: str):
    phone = _phone_dec(phone_enc)
    profile = load_profile(phone)
    name = profile.get("name") or get_contact_name(phone) or phone
    contact = {
        "phone": phone, "phone_enc": phone_enc, "name": name,
        "initials": "".join(w[0].upper() for w in name.split()[:2]) if name else "?",
        "notes": profile.get("notes", ""), "memory_count": 0, "last_seen": None,
    }
    msg_query = request.args.get("msg_q", "").strip()
    message_history = get_message_history(phone, query=msg_query if msg_query else None, limit=200)
    other_contacts = [
        {"phone": c["key"], "phone_enc": _phone_enc(c["key"]), "name": c["name"]}
        for c in get_all_contacts() if c["key"] != phone
    ]
    return render_template("contact.html", page="contact", contact=contact, memories={},
                           message_history=message_history, msg_query=msg_query,
                           other_contacts=other_contacts, nudge_count=0)


@app.route("/dashboard/contact/<phone_enc>/notes", methods=["POST"])
@_require_dashboard_auth
def dash_save_notes(phone_enc: str):
    phone = _phone_dec(phone_enc)
    save_contact_notes(phone, request.form.get("notes", "").strip())
    return redirect(f"/dashboard/contact/{phone_enc}")


@app.route("/dashboard/contact/<phone_enc>/merge", methods=["POST"])
@_require_dashboard_auth
def dash_merge(phone_enc: str):
    phone = _phone_dec(phone_enc)
    target_phone_enc = request.form.get("target_phone", "").strip()
    if target_phone_enc:
        merge_contact(_phone_dec(target_phone_enc), phone)
    return redirect(f"/dashboard/contact/{phone_enc}")


@app.route("/dashboard/search")
@_require_dashboard_auth
def dash_search():
    query = request.args.get("q", "").strip()
    contact_filter = request.args.get("contact", "").strip()
    results = []
    all_contacts = []
    if query:
        all_contacts = [{"phone": c["key"], "name": c["name"]} for c in get_all_contacts()]
        phone = _phone_dec(contact_filter) if contact_filter else None
        index = load_index()
        for r in search_messages(query, phone=phone, limit=50):
            name = (index.get(r["phone"]) or {}).get("name") or r["phone"]
            results.append({
                "contact_name": name, "phone": r["phone"], "phone_enc": _phone_enc(r["phone"]),
                "result_type": "message", "source": r["source"], "content": r["content"],
                "timestamp": r["timestamp"], "score": 1.0,
            })
    return render_template("search.html", page="search", query=query, results=results,
                           contact_filter=contact_filter, category_filter="", scope="messages",
                           all_contacts=all_contacts, nudge_count=0)


@app.route("/dashboard/setup")
@_require_dashboard_auth
def dash_setup():
    checks = [{"name": "Webhook secret", "ok": bool(WEBHOOK_SECRET),
               "detail": "Configured" if WEBHOOK_SECRET else "Missing", "fix_url": None, "fix_text": None}]
    with get_db() as conn:
        stats = {
            "contacts": conn.execute("SELECT COUNT(*) FROM contacts").fetchone()[0],
            "memories": 0,  # assistant data lives in the assistant project now
            "observed": conn.execute("SELECT COUNT(*) FROM observed_messages").fetchone()[0],
            "nudges": 0,
        }
    return render_template("setup.html", page="setup", checks=checks, db_stats=stats, nudge_count=0,
                           telegram_token="", telegram_owner_ids="", telegram_trusted_ids="",
                           telegram_ok=False, telegram_status="")


@app.route("/dashboard/logs")
@_require_dashboard_auth
def dash_logs():
    n = min(int(request.args.get("n", "200")), 1000)
    level_filter = request.args.get("level", "all").lower()
    log_lines = []
    if os.path.exists(_LOG_PATH):
        with open(_LOG_PATH, "r", errors="replace") as f:
            for raw in f.readlines()[-n:]:
                raw = raw.rstrip()
                level = "error" if "ERROR" in raw else "warning" if "WARNING" in raw else "info" if "INFO" in raw else "debug"
                if level_filter == "all" or level == level_filter:
                    log_lines.append({"text": raw, "level": level})
    return render_template("logs.html", page="logs", log_lines=log_lines, level_filter=level_filter,
                           n=n, nudge_count=0, log_path=_LOG_PATH)


@app.route("/dashboard/logs/stream")
@_require_dashboard_auth
def dash_logs_stream():
    """SSE endpoint that tails the log file and pushes new lines to the browser."""
    def generate():
        if not os.path.exists(_LOG_PATH):
            yield "data: [log file not found]\n\n"
            return
        with open(_LOG_PATH, "r", errors="replace") as f:
            f.seek(0, 2)
            while True:
                line = f.readline()
                if line:
                    yield f"data: {line.rstrip()}\n\n"
                else:
                    time.sleep(0.5)
    return Response(generate(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})

# ── Webhooks (ingestion) ──────────────────────────────────────────────────────

@app.route("/observe", methods=["POST"])
def observe():
    """Watcher-mode endpoint — log only, never reply."""
    auth_err = _require_auth()
    if auth_err: return auth_err
    data = request.get_json(force=True, silent=True) or {}
    msg = data.get("data", {}) if "data" in data else data
    from_number = resolve_key(msg.get("contact") or msg.get("from_number", ""))
    content = (msg.get("content") or msg.get("body", "")).strip()
    if not from_number or not content: return "", 200
    save_observed(from_number, content)
    logging.info(f"Observed SMS from {from_number}: {content[:80]}")
    return "", 200


# When set (e.g. http://assistant:5067/reply), active-mode messages are relayed
# to the assistant and its reply is returned as the response body — the phone
# app sends that text back as an SMS. Unset → pure logging.
# VI_REPLY_URL is the legacy name for the same setting.
ASSISTANT_REPLY_URL = os.getenv("ASSISTANT_REPLY_URL") or os.getenv("VI_REPLY_URL", "")


def _handle_sms(from_number: str, content: str):
    """Core SMS pipeline: always log; in active mode also relay to the assistant for a reply."""
    import requests
    from_number = resolve_key(from_number)
    if not from_number or not content:
        return "", 200
    save_observed(from_number, content)
    logging.info(f"Logged SMS from {from_number}: {content[:80]}")
    if ASSISTANT_REPLY_URL:
        try:
            r = requests.post(
                ASSISTANT_REPLY_URL,
                json={"phone": from_number, "content": content},
                headers={"X-Webhook-Secret": WEBHOOK_SECRET},
                timeout=90,
            )
            if r.ok and r.text.strip():
                logging.info(f"Assistant reply for {from_number}: {r.text[:80]}")
                return r.text, 200, {"Content-Type": "text/plain"}
        except Exception as e:
            logging.warning(f"Assistant relay failed ({e}) — message logged, no reply sent")
    return "", 200


@app.route("/webhook", methods=["POST"])
def webhook():
    auth_err = _require_auth()
    if auth_err: return auth_err
    data = request.get_json(force=True, silent=True) or {}
    if data.get("type") != "message.phone.received": return "", 200
    msg = data.get("data", {})
    return _handle_sms(msg.get("contact", ""), msg.get("content", "").strip())


@app.route("/webhook/android-sms", methods=["POST"])
def android_sms_webhook():
    """Adapter for the Android forwarder app's received-SMS webhook."""
    if WEBHOOK_SECRET and not hmac.compare_digest(
        request.headers.get("X-Webhook-Secret", ""), WEBHOOK_SECRET
    ):
        return "Unauthorized", 401
    data = request.get_json(force=True, silent=True) or {}
    if data.get("event") != "sms:received":
        return "ok", 200
    payload = data.get("payload", {})
    phone = re.sub(r"\D", "", payload.get("phoneNumber", ""))
    content = payload.get("message", "").strip()
    logging.info(f"android-sms: SMS from {phone}: {content[:80]}")
    return _handle_sms(phone, content)

# ── MMS ingestion (media-aware) ───────────────────────────────────────────────

# Mounted into the container from a host directory (see docker-compose).
MMS_ATTACH_DIR = os.getenv("MMS_ATTACH_DIR", "/app/attachments")


def _save_mms_attachment(phone: str, att: dict) -> str | None:
    """Decode one base64 attachment to disk under MMS_ATTACH_DIR/<contact>/.
    Returns the '<contact>/<filename>' path, or None if there's nothing to save."""
    b64 = att.get("base64")
    if not b64:
        return None
    key_dir = re.sub(r"[^\w.\-]", "_", phone) or "unknown"
    orig = re.sub(r"[^\w.\-]", "_", att.get("filename") or "mms")
    fname = f"{key_dir}_{int(time.time() * 1000)}_{orig}"
    dest_dir = os.path.join(MMS_ATTACH_DIR, key_dir)
    try:
        os.makedirs(dest_dir, exist_ok=True)
        with open(os.path.join(dest_dir, fname), "wb") as f:
            f.write(base64.b64decode(b64))
    except Exception as e:
        logging.warning(f"MMS attachment save failed ({orig}): {e}")
        return None
    return f"{key_dir}/{fname}"


@app.route("/webhook/mms", methods=["POST"])
def webhook_mms():
    """Media-aware MMS endpoint. Logs the text + saves image/media parts,
    referenced by path in the log. Never replies."""
    if WEBHOOK_SECRET and not hmac.compare_digest(
        request.headers.get("X-Webhook-Secret", ""), WEBHOOK_SECRET
    ):
        return "Unauthorized", 401
    data = request.get_json(force=True, silent=True) or {}
    if data.get("type") != "message.mms.received":
        return "ok", 200
    payload = data.get("payload", {})
    raw_from = (payload.get("phoneNumber", "") or "").split(",")[0].strip()
    phone = resolve_key(re.sub(r"\D", "", raw_from) or raw_from)
    if not phone:
        return "", 200
    text = (payload.get("content") or "").strip()
    embeds = [
        f"[MMS image: {rel}]"
        for att in (payload.get("attachments") or [])
        if (rel := _save_mms_attachment(phone, att))
    ]
    if not text and not embeds:
        return "", 200
    content = "\n".join(([text] if text else []) + embeds)
    save_message(phone, "user", content)
    logging.info(f"MMS from {phone}: {len(embeds)} media, text={text[:60]!r}")
    return "", 200

# ── Read-only JSON API (for assistants and other consumers) ───────────────────────────

@app.route("/api/contacts")
@limiter.exempt
def api_contacts():
    auth_err = _require_auth()
    if auth_err: return auth_err
    return jsonify({"contacts": get_all_contacts()})


@app.route("/api/messages/<contact_key>")
@limiter.exempt
def api_messages(contact_key: str):
    auth_err = _require_auth()
    if auth_err: return auth_err
    key = resolve_key(contact_key)
    since = request.args.get("since", "").strip()
    limit = min(int(request.args.get("limit", "100")), 1000)
    order = request.args.get("order", "asc")
    msgs = get_message_history(key, limit=limit)  # oldest first
    if since:
        msgs = [m for m in msgs if (m["timestamp"] or "") > since]
    if order == "desc":
        msgs = list(reversed(msgs))
    return jsonify({"contact": key, "name": get_contact_name(key), "messages": msgs})


@app.route("/api/search")
@limiter.exempt
def api_search():
    auth_err = _require_auth()
    if auth_err: return auth_err
    q = request.args.get("q", "").strip()
    if not q:
        return jsonify({"error": "q required"}), 400
    contact = request.args.get("contact", "").strip()
    limit = min(int(request.args.get("limit", "50")), 200)
    key = resolve_key(contact) if contact else None
    index = load_index()
    results = []
    for r in search_messages(q, phone=key, limit=limit):
        r["name"] = (index.get(r["phone"]) or {}).get("name") or r["phone"]
        results.append(r)
    return jsonify({"query": q, "results": results})


@app.route("/api/recent")
@limiter.exempt
def api_recent():
    """Most recent observed messages across ALL contacts (an assistant's silent-watch feed)."""
    auth_err = _require_auth()
    if auth_err: return auth_err
    limit = min(int(request.args.get("limit", "15")), 100)
    with get_db() as conn:
        rows = conn.execute(
            "SELECT phone, content, timestamp FROM observed_messages ORDER BY id DESC LIMIT ?",
            (limit,),
        ).fetchall()
    index = load_index()
    messages = [
        {"phone": p, "name": (index.get(p) or {}).get("name") or p, "content": c, "timestamp": t}
        for p, c, t in reversed(rows)
    ]
    return jsonify({"messages": messages})


@app.route("/health")
def health(): return "ok", 200

# ── Startup ───────────────────────────────────────────────────────────────────
# Runs at module import so background threads start under gunicorn too.
# NOTE: gunicorn MUST run with --workers 1 — the export loop is not multi-worker safe.

_started = False

def _startup():
    global _started
    if _started:
        return
    _started = True
    init_db()
    from smslog.sms_exporter import sms_export_loop
    threading.Thread(target=sms_export_loop, daemon=True).start()

_startup()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5066, threaded=True)
